name: Build and Test on Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: go get -u github.com/gin-gonic/gin github.com/gorilla/websocket

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create directories
      run: |
        mkdir -p Uploads outputs
        chmod -R 755 Uploads outputs

    - name: Run application (background)
      run: |
        go run main.go &
        sleep 5

    - name: Test HTTP endpoint
      run: |
        curl -f http://localhost:8080